/*GROUP MEMBERS:     ABDUL-RAZZAQUE-JAWAD.
                     MUHAMMAD RIZWAN KHALID.
  CLASS:             BSCS-6-A.
  IDE USED:          MICROSOFT VISUAL STUDIO.
  PROEJCT#:          03
*/
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
unsigned long long findd(unsigned long long e, unsigned long long phi)
{
	unsigned long long x, y, u, v, m, n, a, b, q, r;
	/* phi = e(0) + phi(1) */
	x = 0; y = 1;

	/* e = e(1) + phi(0) */
	u = 1; v = 0;
	for (a = e, b = phi; 0 != a; b = a, a = r, x = u, y = v, u = m, v = n)
	{
		/* b = aq + r and 0 <= r < a */
		q = b / a;
		r = b % a;

		/* r = Ax + By - aq = Ax + By - (Au + Bv)q = pe(x - uq) + pphi(y - vq) */
		m = x - (u * q);
		n = y - (v * q);
	}

	/* Ax + By = gcd(e, phi) */
	// b contains the gcd and had better be 1
	// d is the sum of x and m.
	return m + x;
}
void main()
{
	char msg[50];
	char msg_temp[50];
	int p = 53;
	int q = 61;
	int n = (p*q);
	int e = 17;
	int d;
	int phie = (p - 1)*(q - 1);		 //Computation of phie so tha it can be used to find d.
	d = findd(e, phie);				//Calling RSA utility function to calculate the value of d.
	int i = 0;
	int y = 0;
	printf("+-----------------------------+\n| RSA Public-key Cryptosystem |\n+-----------------------------+\n\n");
	printf("+-------------------+\n| I. Key Generation |\n+-------------------+\n\n");
	printf("Public key. (e,n) = ( %d,%d)\n",e,n);
	printf("Private key. (d,n) = (%d,%d)\n\n", d, n);
	printf("+-------------------------+\n| II. Cipher and Decipher |\n+-------------------------+\n\n");
	printf("Enter Your Message:  ");
	gets(msg);				//Getting message from the user.
	for (i = 0; msg[i]!='\0'; i++){
		msg_temp[i] = msg[i];		//initializing temporaray array with the string inputed by uset.
	}
	printf("Input. ");
	for (i = 0; msg[i] != '\0'; i++){
		printf("| '%c' ",msg[i]);			//Formating the output as given in sample output.
	}
	for (i = 0; msg[i] != 0; i++){
		if (msg[i] >= 65 && msg[i] <= 90){
			msg[y] = msg[i] - 65;			//initializing A,B,.....,Z, with 1,2,3.......,25.
			y++;
		}
		else if (msg[i] == 32){
			msg[y] = 26;			//initializing the white space with no. 26.
			y++;
		}
		else if (msg[i] == 46){
			msg[y] = 27;			//Initializing the period with no. 27.
			y++;
		}
	}
	printf("|\n       ");
	for (int s = 0; s < y; s++){		//Printing the numbers corresponding to the each letter of the string.
		printf("| %d ", msg[s]);
	}
	printf("|\n\nM.    ");
	for (i = 0; i < y; i=i+2){
			printf("| %c%c ", msg_temp[i], msg_temp[i + 1]);		//Sampling the format as give in sample run.
	}
	printf("|\n");
	int pi[50];
	int k = 0;
	int t = 0;
	for (k = 0; k < y; k = k + 2){
			pi[t] = (msg[k] * 100) + msg[k + 1];		//initiizing another array in such a way that the no. corresponding to
			t++;										//first letter is multiplied with hundred and the no corresponding to second	
	}													//letter is added in previous and this continues till the end of string
	printf("P(M). ");
	for (int u = 0; u < t; u++){
		printf("| %d", pi[u]);							//printing the number generated by using above sequence.
	}
	printf("|\n");
	int ci[50];
	int temp = 1;
	for (int h = 0; h < y; h++){
		for (int v = 1; v <= e; v++){
			temp = temp * pi[h];
			temp  = temp % n;						// Applying the formula of encryption C(P) = P^e(mod (n)) in c format.
		}
		ci[h] = temp;
		temp = 1;
	}
	printf("C(P). ");
	for (int f = 0; f<t; f++){
		printf("| %d", ci[f]);					//Printing the C(P) corresponding to each sequece generated above.
	} 
	printf("|");//ENCRYPTION.
	int m[50];
	for (int c = 0; c < t; c++){
		for (int v = 1; v <= d; v++){
			temp = temp * ci[c];
			temp = temp % n;
		}
		m[c] = temp;
		temp = 1;
	}
	printf("\nD(C). ");
	for (int f = 0; f<t; f++){				//Applying the formula of decryption D(C) = C(P)^d (mod (n)) in C format
		printf("| %d", m[f]);
	}
	int g = 0;
	int u[50];
	for (int f = 0; f<t; f++){
		u[g] = m[f] / 100;
		g++;								// Spliting back the number sequence into numbers having corresponding alphabets
		u[g] = m[f] % 100;
		g++;
	}
	printf("|\n");
	int u_temp[50];
	for (int f = 0; f < g; f++){
		u_temp[f] = u[f];
	}
	for (int f = 0; f < g; f++){
		if (u[f] == 26){
			u[f] = 32;					
		}									//Converting the numbers back to alphabets using ASCII code
		else if (u[f] == 27){
			u[f] = 46;
		}
		else{
			u[f] = u[f] + 65;
		}
	}
	printf("M.    ");
	for (int f = 0; f < g; f=f+2){
		if (u[f + 1] != '\0'){
			printf("| %c%c", u[f], u[f + 1]);
		}
		else{									//printing the result in given format (sample run)
			printf("| %c", u[f]);
		}
	}
	printf("|\n\n");
	printf("Output. ");
	for (i = 0; i < g; i++){
		printf("| %d",u_temp[i]);				
	}
	printf("|\n        ");
	for (int f = 0; f<g; f++){
		printf("| %c", u[f]);
	}
	printf("|");
	getchar();
	getchar();
}